site_name:           Hecke
repo_name:           thofma/Hecke
repo_url:            https://github.com/thofma/Hecke.jl
site_description:    Hecke
site_author:         Tommy Hofmann
theme:               cinder

#extra:
#  palette:
#    primary: 'indigo'
#    accent: 'light blue'

pages:
- Home:                 index.md
- Documentation:
  #- Table of contents:  toc.md
  - Introduction:       number_fields/intro.md
  - Orders and number fields:
    - Introduction:     orders/introduction.md
    - Basics:           orders/orders.md
    - Elements:         orders/elements.md
    - Ideals:           orders/ideals.md
    - Fractional Ideals: orders/frac_ideals.md
  - Abelian groups:
    - Introduction:     abelian/introduction.md
  - Class fields:
    - Introduction:     class_fields/intro.md
  - Factored Elements:
    - Introduction:     FacElem.md
extra_css:
    - assets/Documenter.css
# This are tricks to get syntax highlighting working
# Copied from the Currencies gh-pages in latest/assets
    - application-e2807e330f.css
    - application-f78e5cb881.palette.css

markdown_extensions:
- codehilite
- extra
- tables
- fenced_code
- mdx_math:
    enable_dollar_delimiter: True
- admonition

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

